---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u5cfvtpd/public_html/gate.ukmiptek.org/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R asset $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH